### ISSUE TITLE
ggslackr not posting plot in Channel

### ISSUE THREAD

**Issue by mohan-mishra** [mrkaye97/slackr#100]
The ggslackr function is not posting the ggplot in the channel. However, I can see the file in my workspace(By clicking the three dots in the top right in slack app). What am I missing?
PS: text_slackr is sending the message to the channel

**Comment by haututu** [comment]
Same problem, I suspect this package is broken when using the new webhooky bizzo instead of the old API method.

It doesnt seem like there is a substitute which is better maintained ?

**Comment by yonicd** [comment]
You can try using [slackteams](https://github.com/yonicd/slackteams) to set up your incoming webhook and post to slack with [slackblocks](https://github.com/yonicd/slackblocks).

**Comment by nknauer** [comment]
is there a better solution than above to post ggplots in slack?

**Comment by nknauer** [comment]
@hrbrmstr

**Comment by mrkaye97** [comment]
This is fixed in 2.0.0+
