### ISSUE TITLE
How to get slackr running with Slack Apps?

### ISSUE THREAD

**Issue by nicoschreibt** [mrkaye97/slackr#103]
Guys I'm stuck. I found [this](https://www.infoworld.com/article/3402657/how-to-slack-from-r.html) tutorial for slackr. But it is outdated as slack deleted the legacy token. Is there any advice on how to get slack running now? All information I find is from before Slack Apps.

**Comment by yonicd** [comment]
There is a newer suite of slack packages for R.

Start with [slackteams](https://github.com/yonicd/slackteams) and you’ll get redirected to the other ones.
