### ISSUE TITLE
slackr_bot changing channel names

### ISSUE THREAD

**Issue by nknauer** [mrkaye97/slackr#106]
Is there a way to change the channel directly from slackr_bot instead of what is configured when setting up the app?

```
slackr_bot(head(mtcars), username="slackr", channel="xxxxxxxxx",
           incoming_webhook_url="https://hooks.slack.com/services/xxxxxxxxxx/xxxxxxxxxxxxx")
```

If I change the channel in slackr_bot function it doesn't actually change, it just sticks with the original.

**Comment by obarisk** [comment]
the reason might be.
with *incoming_webhook_uri*, the message goes to the incoming_webhook_uri.

**Comment by nknauer** [comment]
Have you seen this issue in the past as well? If so, how did you modify the webhook?

**Comment by obarisk** [comment]
I create an slack app. And use the api key for the app.
But it might only work for the workspace adminstrator.

**Comment by mrkaye97** [comment]
This issue is happening because `slackr_bot()` relies on a webhook that only is attached to one channel. I will deprecate the channel argument in the next version of `slackr`
