### ISSUE TITLE
x Problem with `id`

### ISSUE THREAD

**Issue by nknauer** [mrkaye97/slackr#107]
I am not an admin so I can't change the scopes. I can send slackr_bot messages to a channel I set up in the creation of the app in UI but doing the below does not work. Has anyone found a solution to this?

I created a txt file called: test.txt

Within that txt file it looks like this:
```
api_token: xxxxxxxxxxxx
channel: #channel_name
username: myusername
incoming_webhook_url: https://hooks.slack.com/services/xxxxxxxxxxx/xxxxxxxxxxxxx

```

Then I want to simply send a message but eventually I would like to run the function 
ggslackr(qplot(mpg, wt, data=mtcars))

```
slackr_setup(config_file = "test.txt")
my_message <- paste("I'm sending a Slack message at", Sys.time(), "from my R script.")
slackr_msg(my_message, channel = "#channel_name", as_user=F)

```

Here is the error message:
```
Error: Join columns must be present in data.
x Problem with `id`.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In structure(vars, groups = group_vars, class = c("dplyr_sel_vars",  :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

**Comment by mrkaye97** [comment]
Try  `remotes::install_github('mrkaye97/slackr')` now and see how it works. New version should be mostly fixed (but probably still some bugs). This error was caused by an issue with the Slack API

**Comment by kburnham** [comment]
When I install from that location and then do `library(slackr)` I get:
```
Error: package or namespace load failed for ‘slackr’:
 .onLoad failed in loadNamespace() for 'texPreview', details:
  call: FUN(X[[i]], ...)
  error: neither tlmgr or mpm are installed and in %PATH%
```

**Comment by mrkaye97** [comment]
@kburnham See #110 and #113

**Comment by xinye1** [comment]
@kburnham it's likely that you don't have TeX on your machine. #113 removes the dependency of texPreview unless you call `tex_slackr()` so your error should go away, once @mrkaye97 merges my PR :)

**Comment by nknauer** [comment]
Will using the package through GitHub work for ggslackr as well?

**Comment by mrkaye97** [comment]
@xinye1 I don't have write access on the repo so I can't merge the PR :/

If you clone my fork and put in a PR there I'll gladly merge it!

**Comment by mrkaye97** [comment]
@nknauer Yes, it should

**Comment by xinye1** [comment]
@mrkaye97  sure thing

**Comment by nknauer** [comment]
This is probably an issue I need to bring up with databricks but I was not able to download this package. 

remotes::install_github('mrkaye97/slackr')
library(slackr)

ERROR: configuration failed for package ‘magick’
* removing ‘/databricks/spark/R/lib/magick’
Error : Failed to install 'slackr' from GitHub:
  (converted from warning) installation of package ‘magick’ had non-zero exit status

**Comment by mrkaye97** [comment]
@nknauer Try `install.packages("magick")` first. If that works and fixed the issue, I'll add some tests and stuff to avoid this as a problem

**Comment by nknauer** [comment]
No luck installing that package specifically:

```
Installing package into ‘/databricks/spark/R/lib’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/magick_2.5.2.tar.gz'
Content type 'application/x-gzip' length 4757100 bytes (4.5 MB)
==================================================
downloaded 4.5 MB

* installing *source* package ‘magick’ ...
** package ‘magick’ successfully unpacked and MD5 sums checked
** using staged installation
Package Magick++ was not found in the pkg-config search path.
Perhaps you should add the directory containing `Magick++.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Magick++' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lMagick++-6.Q16
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the Magick++ library. Try installing:
 - deb: libmagick++-dev (Debian, Ubuntu)
 - rpm: ImageMagick-c++-devel (Fedora, CentOS, RHEL)
 - csw: imagemagick_dev (Solaris)
 - brew imagemagick@6 (MacOS)
For Ubuntu versions Trusty (14.04) and Xenial (16.04) use our PPA:
   sudo add-apt-repository -y ppa:cran/imagemagick
   sudo apt-get update
   sudo apt-get install -y libmagick++-dev
If Magick++ is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a Magick++.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: Magick++.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘magick’
* removing ‘/databricks/spark/R/lib/magick’

The downloaded source packages are in
	‘/tmp/RtmppeAr32/downloaded_packages’
```

**Comment by mrkaye97** [comment]
@nknauer Oh, that's a pretty helpful error actually. You can probably just `brew imagemagick@6` (depending on the OS). Thanks for your patience btw.

**Comment by nknauer** [comment]
Is that an R function? This is through databricks by the way

**Comment by mrkaye97** [comment]
Ah, no. You'd need to run that in the command line, which should work if you have Homebrew installed (Linux / Unix). There are other solutions for windows 

Edit: haven't used Databricks, so can't speak to that. I know how to do it in Docker though if that'd be helpful

**Comment by xinye1** [comment]
Databricks typically runs on Linux, you need to install Magick on the cluster. Have a look at this https://docs.databricks.com/libraries/index.html

To install that you need to run shell commands in the notebook, the commands being the ANTICONF section of your error message, and check out how to run commands here https://docs.databricks.com/notebooks/notebooks-use.html#mix-languages

If there are more issues contact your Databricks sysadmin or customer support

**Comment by nknauer** [comment]
I tried downloading this version of the package on my local computer too. I am able to install the package but then when I do library(slackr). This error message appears:

```
Error: package or namespace load failed for ‘slackr’:
 .onLoad failed in loadNamespace() for 'texPreview', details:
  call: FUN(X[[i]], ...)
  error: neither tlmgr or mpm are installed and in %PATH%
```

And then when I try and install tlmgr it fails saying it is unavailable and then after a successful install of mpm, same error message.

**Comment by mrkaye97** [comment]
@nknauer see #110

**Comment by nknauer** [comment]
Thanks I was able to load the package locally! I can create a new ticket for ggslackr so you can close this out but there is still an issue with using that function. I followed your directions on the main github page and get the below error: 

There was no error with slackrSetup which is great news! Everything after does not work though.

```
slackrSetup(channel="#my_channel_name", 
            incoming_webhook_url="https://hooks.slack.com/services/xxxxxxxxxx/xxxxxxx")

dev.slackr("#my_channel_name")
ggslackr(qplot(mpg, wt, data=mtcars))
Error: `x` and `y` must share the same src, set `copy` = TRUE (may be slow).
```

**Comment by mrkaye97** [comment]
@nknauer This issue happens when `slackr` isn't seeing the channel you're pointing it at. When I have some time, I'll write some more informative error messages and update `mrkaye97/slackr` so it's more clear. For now, this is likely either a) a scopes issue or b) happening because your channel is private. See [this comment](https://github.com/hrbrmstr/slackr/issues/114#issuecomment-740284698) in #114 for details on that. My advice is to make the channel public and add the scopes that I reference in that comment, and then try reinstalling the app and running `slackr_setup()` again. You should also test that your Slack app is seeing the channel you want by using the API `conversations` tester that I linked in that comment. Let me know if this solves it.

**Comment by nknauer** [comment]
It's probably the scopes. Will try that out and let you know how it goes. Thanks for the prompt responses! Below is what I have currently.
![image](https://user-images.githubusercontent.com/23511145/102002977-bc8cf180-3cb6-11eb-8a01-4e153871540b.png)

**Comment by mrkaye97** [comment]
Sure thing! Happy to help.

**Comment by mrkaye97** [comment]
@nknauer I just updated `mrkaye97/slackr`, so if you run `devtools::install_github('mrkaye97/slackr')` and try to get set up, you should get some more informative error messaging now.

**Comment by mrkaye97** [comment]
@nknauer Update #2: I'm now officially a maintainer, so now `devtools::install_github('hrbrmstr/slackr')` will install the newest version, and it will also be back up on CRAN soon.

**Comment by nknauer** [comment]
Great thanks for the update!

**Comment by nknauer** [comment]
Great, thanks for the update!
