### ISSUE TITLE
SlackrUpload Error

### ISSUE THREAD

**Issue by nknauer** [mrkaye97/slackr#115]
I am trying to upload a file to a slack channel in databricks. The function runs with no error but nothing uploads to the channel. I then try running it in RStudio and do get an error which may help solve the problem.

Anyone try this in the past? 

    httr::with_verbose(slackrUpload('file.csv', channels = "channel_a",
                api_token = "Bot User OAuth Access Token"))

    Error: Join columns must be present in data.
    x Problem with `id`.
    Run `rlang::last_error()` to see where the error occurred.
    In addition: Warning message:
    In structure(vars, groups = group_vars, class = c("dplyr_sel_vars",  :
      Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
      Consider 'structure(list(), *)' instead.

My Oath Scopes are as follows: 

    files:write
    incoming-webhook

**Comment by mrkaye97** [comment]
This is likely a scope issue. I think you at least need `channels:read`, `channels:write`, `groups:read`, `im:read`, `users:read`, and `users.profile:read` under `Bot Token Scopes`

**Comment by aniruhil** [comment]
Thanks @mrkaye97 ... activating these scopes solved my problem with an error message reported by other users in #114

**Comment by mrkaye97** [comment]
@aniruhil No problem! Glad to help
