### ISSUE TITLE
Support R version

### ISSUE THREAD

**Issue by woowahan-jaehoon** [mrkaye97/slackr#123]
Hi.

I checked that slackr 2.0.1 support only over R 4.0.0 but I think that many users are using under R 4.0.0 and I do.

Could you change to back R depends version? (https://github.com/hrbrmstr/slackr/blob/master/DESCRIPTION)

I checked that it works when I changed R depends version to over 3.0.0 and I used R 3.6.3.

**Comment by woowahan-jaehoon** [comment]
I checked commit about R depends version was changed, but I think that it have no something change about syntax, etc.
https://github.com/woowahan-jaehoon/slackr/commit/3e76aa09f4537160557bd9be49a686491bf0f7c7

**Comment by mrkaye97** [comment]
Yes, if it works on 3.6.3, that's fine. I will test first.

@hrbrmstr any objection to me setting up Github Actions to run `devtools::check()` on pushes? That'd make things like testing multiple OS / R versions pre-merge easier.

**Comment by mrkaye97** [comment]
This is done as of `slackr 2.0.2`. Thanks for putting in the request!
