### ISSUE TITLE
Can't Install Slackr in Databricks

### ISSUE THREAD

**Issue by nknauer** [mrkaye97/slackr#133]
Slackr installation was working fine until this week. 

When I run the code:

install.packages('slackr')
library(slackr)

Error message:
Error in library(slackr) : there is no package called ‘slackr’ Error in library(slackr) : there is no package called ‘slackr’
Error in library(slackr) : there is no package called ‘slackr’
In addition: Warning message:
package ‘slackr’ is not available (for R version 3.6.3)

**Comment by mrkaye97** [comment]
This is because the CRAN version requires `R > 4.0.0`. Use `devtools::install_github('mrkaye97/slackr')` instead

**Comment by nknauer** [comment]
When I download the package via databricks using `devtools::install_github('mrkaye97/slackr')` 

Error : package or namespace load failed for ‘slackr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): Error : package or namespace load failed for ‘slackr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.7 is already loaded, but >= 0.4.9 is required

**Comment by mrkaye97** [comment]
Try restarting R and updating `rlang` to `0.4.9+` before you install `slackr` or try installing with `dependencies = TRUE`

**Comment by nknauer** [comment]
Same error when I restart the cluster in databricks:
library(devtools)
install_version("rlang", "0.4.9")
devtools::install_github('mrkaye97/slackr', force = TRUE)
library(slackr)


Error : package or namespace load failed for ‘slackr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): Error : package or namespace load failed for ‘slackr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.7 is already loaded, but >= 0.4.9 is required

**Comment by mrkaye97** [comment]
~Can you make a reprex out of this? Just copy this:~

nvm, it won't like the `reprex`. It just looks to me like `rlang` hasn't updated based on the error message (`0.4.7` is already loaded). you might need to force install it or install from CRAN (both should give you `0.4.9`). regardless, this isn't a `slackr` issue I don't think
