### ISSUE TITLE
ggslackr quietly fails but text_slackr posts

### ISSUE THREAD

**Issue by henryhuang1** [mrkaye97/slackr#134]
I'm on slackr version 2.0.1. 
Here's my slackr setup:
`slackr_setup(channel = "#channel", 
               username = "abc.xyz@email.com", 
               icon_emoji = "",
               incoming_webhook_url = "https://hooks.slack.com/services/XXXXXXXX/XXXXXXXX/XXXXXXXXXXXXXX",
               bot_user_oauth_token = "abcd-1234567890-111111111111111111-22222222222222222-3333333333333333333333333333333",
               config_file = "~/.slackr", 
               echo = FALSE)`

With this set up, I can post `text_slackr("hello")` to #channel without fail, but ggslackr does not post anything. For example, `ggslackr(qplot(mpg, wt, data=mtcars))` won't post anything and doesn't return an error. 

In the Github page for slackr, I see this under Known Issues:
`Depending on your scopes, slackr could quietly fail (i.e. not throw an error, but also not post anything to your channel). If this happens, try explicitly adding the slackr app to your channel in your Slack workspace.` 
I've been looking for the slackr app but haven't found it. Does anyone have a link to the app so that I can try it out and see if ggslackr works? Thanks

**Comment by mrkaye97** [comment]
Hi Henry,

I'll reword that bit in the `README`, since it's confusing. You're looking in the right place, though. Here's what I'd try:

In your slack channel, type `\invite @your_app_name` and you should see a message along the lines of "Matt just added your_app_name to this channel". Once you've done that, give `ggslackr()` a shot again.

Also, what scopes do you have enabled? Sometimes this can happen if `chat:write:public` isn't enabled. Let me know how it goes

**Comment by henryhuang1** [comment]
We realized that we actually had to do this step first:
```
Creating a fully-functional multi-channel bot

Creating a bot user to send messages to multiple channels, including plots, tables, files, etc. as well as deleting messages, reading the channels in a workspace, etc.
```

We followed the instructions exactly as documented here: https://github.com/mrkaye97/slackr/blob/master/vignettes/scoped-bot-setup.Rmd
Then when we tried to run slackr_setup, we ran into an error:
```
1. setUpSlackConnection()
2. slackr_setup(channel = "abc", 
                           incoming_webhook_url = "webhook", 
                           bot_user_oauth_token = "token", config_file = "~/.slackr", echo = FALSE)
3. slackr_createcache(Sys.getenv("SLACK_BOT_USER_OAUTH_TOKEN"))
4. slackr_census(bot_user_oauth_token)
5. slackr_ims(bot_user_oauth_token)
Error in if ((nrow(ims) == 0) | (nrow(users) == 0)) { : argument is of length zero
```
The actual token and webhook used were the ones from the Slackr app that we set up from here: https://github.com/mrkaye97/slackr/blob/master/vignettes/scoped-bot-setup.Rmd

I also tried running the function without `config_file` and `echo` but ran into the same error. 

Sorry this question got off topic

**Comment by mrkaye97** [comment]
Can you try upgrading to version `2.1.1` with `devtools::install_github('mrkaye97/slackr')` and see if that solves the issue? `slackr_createcache()` no longer exists. 

Also, FYI `slackr_setup()` only needs either the config file or to be explicitly passed

**Comment by henryhuang1** [comment]
Great, it's posting again! Thanks for the help!
