### ISSUE TITLE
slack_setup() error

### ISSUE THREAD

**Issue by marolopnaiba** [mrkaye97/slackr#135]
Hi, sorry for my silly questions. Just working on slack-R recently.
I've worked on an alert system that sends a customized message into Slack.

It keeps getting an error when I try slackr_setup. Below is the r-script and error code
```
slackrSetup(channel="#test_slack_alert_mn", 
            incoming_webhook_url="xxxx-xxxx-xxxx",
            bot_user_oauth_token='xxxx-xxxx-xxxx')
```

```
Warning: The slack API returned an error: missing_scope
Error in slackr_census(bot_user_oauth_token) : 
  slackr is not seeing any channels in your workspace. Are you sure you have the right scopes enabled? See the readme for details.
```
I've added several scopes in my app configuration but keep getting the above error.

What is missing in this and is there anything I could do to fix this?
Thank you in advance.

**Comment by mrkaye97** [comment]
No worries! What scopes do you have enabled for your app? The ones you need are listed in the readme

**Comment by marolopnaiba** [comment]
Hi mrkaye97 thank you! it's worked now.
