### ISSUE TITLE
slackr username issue

### ISSUE THREAD

**Issue by rkersey8208** [mrkaye97/slackr#138]
For some reason, running a slackr_upload command posts a message in slackr from the bot I created. However, running slackr and slackr_msg commands sends a message from slackr itself:

![image](https://user-images.githubusercontent.com/78451639/106809780-16b48e00-663a-11eb-9b4b-aa7b66365548.png)

**Comment by mrkaye97** [comment]
As it turns out, this is actually an issue with the Slack API. The `files.upload` endpoint doesn't allow for a username or an icon emoji to be specified. Closing this now.
