### ISSUE TITLE
Dependency needs updating in description

### ISSUE THREAD

**Issue by MaxineTheCat** [mrkaye97/slackr#147]
Depends:
    R (>= 3.3.0)

works on 4.0 and higher as stated in CRAN
https://cran.r-project.org/web/packages/slackr/index.html

**Comment by mrkaye97** [comment]
@MaxineTheCat the CRAN version is `2.0.1` and relies on `R >= 4.0.0`. This version (dev, GitHub) is `2.1.0+` and doesn't. CRAN will be updated eventually. For now, use `devtools::install_github("mrkaye97/slackr")` to install the package

**Comment by MaxineTheCat** [comment]
got it! thanks! worked w/ devtools::install_github("mrkaye97/slackr"). appreciate the quick response. great package!

**Comment by mrkaye97** [comment]
Glad to hear it @MaxineTheCat. and thanks!
