### ISSUE TITLE
Sending downloadable plots to slack

### ISSUE THREAD

**Issue by tiagobrc** [mrkaye97/slackr#163]
Can slackr send the ggplots as pdf files to be download to slack?

**Comment by mrkaye97** [comment]
@tiagobrc Not yet, but thanks for the suggestion! This should be an easy change to make. I will open `slackr 3.1.0` with this update and will close this issue when it goes live

**Comment by mrkaye97** [comment]
@tiagobrc This should be live now

**Comment by tiagobrc** [comment]
@mrkaye97 amazing! Thank you for this awesomepackage!

**Comment by mrkaye97** [comment]
Sure thing @tiagobrc! Let me know if you've got any other questions. Thanks for putting in this feature request!
