### ISSUE TITLE
Ability to tag someone in the `initial_comment` argument of `slackr_upload()`

### ISSUE THREAD

**Issue by pstraforelli** [mrkaye97/slackr#178]
**Is your feature request related to a problem? Please describe.**

It does not appear that I can tag someone in the `initial_comment` argument (e.g. " @pstraforelli hello" ) of `slackr_upload()`. It just ends up showing as plain text and the member is not notified.

**Describe the solution you'd like**
Being able to tag someone would be useful in a group channel in order to alert them of a new file available to them.

**Describe alternatives you've considered**
For now, I'm sending a separate `slackr_msg()` but this feels less efficient.

**Comment by mrkaye97** [comment]
hey @pstraforelli, thanks for the issue! I'll look into it in the next few days. Or if you're comfortable with it and would like to, feel free to open a PR with a fix!

**Comment by mrkaye97** [comment]
alright @pstraforelli, so I checked into this. and TL;DR: I don't think there's anything to be done. Your workaround sounds like quite a good one.

The `initial_comment` is correctly passed through to the API call itself here: https://github.com/mrkaye97/slackr/blob/master/R/call_slack_internals.R#L118

which to me says that if you're not seeing your tags show up, then maybe the API doesn't allow for that functionality. I'm going to close this issue as I don't see anything to be done here, but let me know if my understanding is incorrect and feel free to reopen if it is!

**Comment by pstraforelli** [comment]
Fair enough Matt, thanks for looking into it.
