### ISSUE TITLE
Custom slackr usernames

### ISSUE THREAD

**Issue by marshallpayne415** [mrkaye97/slackr#179]
Hey there. First, thanks for such a great package. I use it daily and it's awesome.

My question is about the `username` parameter of the `slackr_msg()` function. I use that for custom reporting in order to add a little context/detail to the message.

Here's a quick reprex (although a full reprex is tough here without a full Slack setup), but just so it's clear what I mean:
```
slackr::slackr_msg(
  txt = "Here's a sweet message.",
  channel = "#channel_to_send_to",
  username = "Custom Username"
)
```
So it's a message that I expect to have the username of **Custom Username**.

Until a couple weeks ago (maybe coinciding with the October update, not sure), that's the username that I would see in the message, both on the desktop app, desktop web browser, and mobile apps.

What's happening now is that the custom username is indeed showing up (i.e., the message is coming "from" **Custom Username** on both the desktop app and on my laptop's web browser).

However, it is not working on my mobile (iPhone) app - the username is coming through as **slackr**.

Did something change with the package that would explain this new behavior?

I've looked around online for potential reports of this, but haven't seen anything so I figured I'd drop a note here.

Thanks!

**Comment by mrkaye97** [comment]
hey @marshallpayne415, based on your description, unfortunately this sounds to me like a bug in Slack itself. If you see the username in your posts on desktop but not mobile, it seems like the username you're seeing is outside of `slackr`'s control at that point. I'd just give it a bit to see if the issue goes away in future updates. Sorry I couldn't be more help :/

**Comment by marshallpayne415** [comment]
@mrkaye97 Gotcha. Yeah I'm hoping that it resolves itself soon as well. The weirdest part is that when my screen is locked and I get a notification, the custom user name shows up, but then when I open the app it goes back to "slackr".

**Comment by mrkaye97** [comment]
hah yeah, that's bizarre. honestly, slack has been a little buggy for me recently too so maybe they're just having some issues 😂
