### ISSUE TITLE
Hi, Can we send messages to slack and ask Claude(ai app) to answer?

### ISSUE THREAD

**Issue by yuanqingye** [mrkaye97/slackr#193]
I successfully connected slack with my r terminal and typing:
slackr('I want to talk with you Claude','@Claude')

I see my message in the webpage, but the claude didn't response to my message.

![image](https://github.com/mrkaye97/slackr/assets/4927499/715b1f75-834f-4c36-bb08-fcf23be4751b)

**Comment by mrkaye97** [comment]
I think this will be resolved if you use `slackr_msg` instead of `slackr`

**Comment by yuanqingye** [comment]
> I think this will be resolved if you use `slackr_msg` instead of `slackr`

Hi
Thank you very much for the very quick reply

yes, the message is no longer in r-format

but the Claude app still not respond to me.

if I type in @Claude, the font is in blue, while the message sent by slackr_msg the @Claude is just what it is.

![image](https://github.com/mrkaye97/slackr/assets/4927499/5fc30473-fe7f-4b63-88c8-9bf2386367f2)

**Comment by mrkaye97** [comment]
It looks to me like `@claude` isn't actually being tagged. I'll poke around a little bit in the API docs, but I'm not sure off the top of my head what's happening here. it might be that the API doesn't like tagging a bot much, but I'm not sure

**Comment by yuanqingye** [comment]
> 

OK, Thank you, keep me informed if there is any intuitions you get from this issue
