### ISSUE TITLE
Allow user to set config_file via environment variable

### ISSUE THREAD

**Issue by botan** [mrkaye97/slackr#194]
Currently, the default value for the `config_file` argument is `"~.slackr"`
```r
slackr_setup(
  channel = "#general",
  username = "slackr",
  icon_emoji = "",
  incoming_webhook_url = "",
  token = "",
  config_file = "~/.slackr",
  echo = FALSE,
  cache_dir = ""
) 
```
and if a user need to use another path, they have to set it in every function call explicitly e.g.
```r
slackr_setup(config_file = "/etc/slackr")
```
however, this could be easily solved by setting an environment variable in `.Renviron` and passing it while keeping the default value the same like below
```r
slackr_setup(
  channel = "#general",
  username = "slackr",
  icon_emoji = "",
  incoming_webhook_url = "",
  token = "",
  config_file = Sys.getenv("SLACKR_CONFIG_FILE", unset = "~/.slackr"),
  echo = FALSE,
  cache_dir = ""
) 
```
Happy to make a PR if you think that's okay.

**Comment by mrkaye97** [comment]
Great idea! If you're willing to submit a PR I'd be happy to review + get it shipped. Thanks!

**Comment by mrkaye97** [comment]
Still need to merge in -- will get around to this in a bit
