### ISSUE TITLE
dplyr error

### ISSUE THREAD

**Issue by konradjk** [mrkaye97/slackr#25]
Hi all,

Getting the following error with slackr after the update that uses dplyr (perhaps due to dplyr version mismatch?). Any ideas?

```
> library(slackr)
> slackrSetup()
> plot(1:10, 1:10)
> dev.slackr()
Error: data_frames can only contain 1d atomic vectors and lists
```

```
> packageVersion('dplyr')
[1] '0.4.3'
> packageVersion('slackr')
[1] '1.3.1.9001'
```

**Comment by konradjk** [comment]
Actually, narrowed this down to something possibly a bit more pernicious. Seems the line (R/slackr_utils.R:122):

```
left_join(users, ims, by="id")
```

is tripping it up. But the problem might actually lie in Slack's API? If I switch the left_join with a merge, there are actually no overlapping individuals (seems `ims` has a `user` column that now cross-references to `id` column in `users`). When I switch that to:

```
merge(users, ims, by.x="id", by.y='user')
```

it works - I've put that in my copy for now, but won't pull request for now if you want to keep things in `dplyr`.

Also, probably unrelated, `users` has 2 fields called `real_name`.

**Comment by zaret-rocket** [comment]
@konradjk I used your fix and it resolved this issue for me as well. Thank you.
