### ISSUE TITLE
gglackr does not work

### ISSUE THREAD

**Issue by upravitelev** [mrkaye97/slackr#27]
Hi!
thanks a lot for your package. unfortunately I have several troubles with the `ggslackr` function.
first, this function changes the locale language settings (thanks to `Sys.setlocale("LC_ALL", "C")` expression). I think it would be great to use the `on.exit` for restoring locale settings.

and second, this function does not work, as far as I see:

```
> ggslackr(pic, channels = "upravitelev")
Response [https://slack.com/api/files.upload]
  Date: 2015-12-01 15:32
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 53 B

??????????????:
1: Removed 34 rows containing missing values (stat_smooth). 
2: Removed 54 rows containing missing values (stat_smooth). 
3: Removed 88 rows containing missing values (geom_path). 
4: Removed 2 rows containing missing values (geom_path). 
5: Removed 3 rows containing missing values (geom_path). 
6: Removed 3 rows containing missing values (geom_path).
```

and nothing appears in my slackbot (`pic` is the ggplot-object)
could you help me with it?

**Comment by markdanese** [comment]
I had the same problem.  It does work for me if I create a private channel and post the ggplot figure to the private channel.  This seems to be related to closed issue #3.  I am using the latest version from github.

**Comment by upravitelev** [comment]
@markdanese 
I found the solution for sending ggplot-objects to slack, but it does not requires `slackr`:

```
gg_slack <- function(gg, channel) {
  ftmp <- tempfile(fileext = ".png")
  ggsave(gg, filename = ftmp)
  httr::POST(url = "https://slack.com/api/files.upload",
             body = list(file = httr::upload_file(ftmp), 
                         token = "your token", 
                         channels = channel))
  httr::POST(url = "https://slack.com/api/chat.postMessage",
             body = list(token = "your token",
                         channel = channel,
                         text = "new graph is here!"))
  on.exit(file.remove(ftmp))
}
```

**Comment by hrbrmstr** [comment]
I have made changes in the 1.4 release. `ggslackr` works (tested against everything but private groups since i don't have a paid Slack anymore)
