### ISSUE TITLE
Ability to listen to messages sent from slack

### ISSUE THREAD

**Issue by jemus42** [mrkaye97/slackr#29]
I'm assuming this is wishful thinking, but can you add support for [the rtm](https://api.slack.com/rtm)?

Sending stuff from R to slack is cool 'n all, but kicking off a script or something from inside slack and have the result posted to a channel? That would be fancy.

**Comment by hrbrmstr** [comment]
Take a look at https://github.com/jayjacobs/slackr

**Comment by jemus42** [comment]
Any plans on this one? I was hoping to write a simple slackbot in R, but I haven't made any real progress so far.

**Comment by hrbrmstr** [comment]
Well, as I said, there's code in that linked repo. PRs welcome! I'm not in any Slacks right now so it'd be a bear to test. I am, however, hacking on [this](https://github.com/hrbrmstr/irced).

**Comment by raybuhr** [comment]
not exactly "listening" to messages, but I have a function that gets messages from the channels.history endpoint that I used to check if new messages contain keywords/emoji. I'll submit a PR.
