### ISSUE TITLE
dev.slackr not working

### ISSUE THREAD

**Issue by eusebe** [mrkaye97/slackr#3]
Hi,

Thank you for this wonderfull package!

I think I figure out how to configure the package: slackr(), slackrChannels(), and slackrUsers() are working perfectly.

But graphic related functions give:

> dev.slackr("#general")
> Erreur dans `[.data.table`(groups, , 1:2, with = FALSE) : j out of bounds
> ggslackr(qplot(mpg, wt, data=mtcars))
> Erreur dans `[.data.table`(groups, , 1:2, with = FALSE) : j out of bounds

Did I miss something?

Again, thank you very much.

**Comment by hrbrmstr** [comment]
I'll definitely take a poke. Do you have some example graphics code that posted to a device right before that call I could use to re-create? (it works for all our tests so far)

**Comment by hrbrmstr** [comment]
Do you have any private groups? The graphics code ends up having to call the file upload API and that requires translating from "#name", "@name" and "name" to the internal IDs. If you don't have any private groups, that's probably the culprit.

**Comment by eusebe** [comment]
I have created a dummy private group, and you're right: it's working.
(This should probably be documented).

Thanks!

**Comment by hrbrmstr** [comment]
Thx for testing and filing the issue! I just pushed new code up that doesn't require private groups to be setup in order to work (1.2.1).

**Comment by eusebe** [comment]
Woo, that was quick.

**Comment by ghost** [comment]
I get the following errors when running the `ggslackr` / `dev.slackr` examples from the manual:

`ggslackr(qplot(mpg, wt, data=mtcars))
Error in rbindlist(l, use.names, fill) : 
  Item 2 has 2 columns, inconsistent with item 1 which has 3 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.`

I get the same error message with any other ggplot code I run. i.e.

`ggslackr(ggplot(iris, aes(x = Species, y = Sepal.Width, fill = Species)) + geom_bar(stat="identity"))`

and yes, I created a private group in Slack. The plots in R are created as expected without errors. 
I can send messages using `slackr` just fine. 
I am using R 3.1.1 and installed the latest slackr-package from github.
