### ISSUE TITLE
icon_emoji bug?

### ISSUE THREAD

**Issue by havlikp** [mrkaye97/slackr#31]
Hello, can anyone please help me figure out how to use _icon_emoji_?

```
slackrSetup(channel = "@petr", username = "happy-data", icon_emoji = ":bar_chart:", api_token = "xxx")
slackr("test", channel = "@petr")
```

Still results in using the default icon. Username works though. Thanks!

**Comment by jh-206** [comment]
I'm having the same issue. My team wanted to use this functionality to get updates on automated code runs, with a happy face when the code successfully runs and a sad face when an error is thrown.

`slackr("Good Message", channel = "xxx", icon_emoji = ":grinning:")`

Just wanted to check if there has been any development on this issue
Best

**Comment by nataliagalant** [comment]
I am having the same issue here with icon_emoji. Has this been resolved lately? 
`slackr_msg(text = 'new text', as_user=FALSE, channel='@me', username='bot', icon_emoji = ":cat:")`

Username changes but icon_emoji does not.

**Comment by nataliagalant** [comment]
@havlikp @jh-206 Work around: 
I think there is an issue with the package itself. The function is defined as : 

`function (txt = "", channel = Sys.getenv("SLACK_CHANNEL"), username = Sys.getenv("SLACK_USERNAME"), 
    icon_emoji = Sys.getenv("SLACK_ICON_EMOJI"), api_token = Sys.getenv("SLACK_API_TOKEN"), 
    ...) 
{
    if (api_token == "") {
        stop("No token specified. Did you forget to call slackr_setup()?", 
            call. = FALSE)
    }
    if (icon_emoji != "") {
        icon_emoji <- sprintf(", \"icon_emoji\": \"%s\"", icon_emoji)
    }
    output <- paste0(txt, collapse = "\n\n")
    loc <- Sys.getlocale("LC_CTYPE")
    Sys.setlocale("LC_CTYPE", "C")
    on.exit(Sys.setlocale("LC_CTYPE", loc))
    resp <- POST(url = "https://slack.com/api/chat.postMessage", 
        body = list(token = api_token, channel = slackr_chtrans(channel), 
            username = username, icon_emoji = icon_emoji, text = output, 
            as_user = TRUE, link_names = 1, ...))
    warn_for_status(resp)
    return(invisible())
}`


The if statement that parses the 'icon_emoji' input results in a string of text that looks like: 
`
, \"icon_emoji\": \":zzz:\"
`
(assuming that 💤 is the emoji input) 

a workaround could be to post to the api directly via the POST function: 
`output <- 'some text'`
`output <-  paste0(output, collapse = "\n\n")`
`resp <- POST(url = "https://slack.com/api/chat.postMessage", 
             body = list(token = api_token, channel = slackr_chtrans(channel), 
                         username = username, icon_emoji = ':zzz:', text = output, 
                         as_user = FALSE, link_names = 1))`

**Comment by yonicd** [comment]
you can pass the emoji as part of the msg

```r
slackr_msg(txt = ':zzz:')
slackr_msg(txt = ':face_with_rolling_eyes:')
```

<img width="188" alt="screen shot 2017-10-30 at 18 39 06" src="https://user-images.githubusercontent.com/1755487/32199139-a8d687e2-bda1-11e7-88d9-1f503c6d52f7.png">

@hrbrmstr is the `icon_emoji` param a legacy param?

**Comment by jh-206** [comment]
Thanks. I like using slackr() because it makes it obvious visually which messages were sent from R and which messages were not. But the emoji will be super useful for scanning for error messages, so I guess I'll use slackr() to send the system time and potential error messages, and then use slackr_msg() after to send emoji indicating success or error.

Appreciate the help!

**Comment by yonicd** [comment]
It sounds like you would be better off to use ‘register_onexit’ and send a summary output to slack when your process is done. See bottom of readme for examples

**Comment by jh-206** [comment]
Yeah hadn't seen that function as I've been working off the CRAN version of the package. Will look to incorporate, thanks

**Comment by yonicd** [comment]
Closing.
