### ISSUE TITLE
slackr_upload() not working?

### ISSUE THREAD

**Issue by sco-lo-digital** [mrkaye97/slackr#34]
i try to upload my csv like this

`slackr_upload("zips.csv")`

nothing happens. no error, and no file on slack. 

been able to use the functions like `slackr()` and `slackr_users` just fine. am I doing something wrong?

tried cran and dev version.

**Comment by hrbrmstr** [comment]
testing now

**Comment by hrbrmstr** [comment]
I tried this on 3 slacks both with and without a `channel` parameter and it works fine. You can get (very verbose) debugging messages with `httr::with_verbose(slackr_upload("test.csv"))`. Can you sanitize and post the output?

**Comment by sco-lo-digital** [comment]
Ok, I think by sanitize you mean clear my workspace? Sorry. 

Cleared my workspace and tried again and it did not work. But, at your (sort of) suggestion I tried with `channel` parameter in `slackr_upload` and that made the difference - it worked. Not sure why, since I passed the `channel` to `slackrSetup` previously? At any rate I will close the issue and thank you!

**Comment by karina-rebuli** [comment]
The same for me, slackr_upload just worked with explicit arg channels.
