### ISSUE TITLE
SlackrUpload not including all contents from CSV file

### ISSUE THREAD

**Issue by raybuhr** [mrkaye97/slackr#35]
For some reason, the SlackrUpload function is not pushing each line of a csv file to the file uploaded to a designated Slack channel. The csv file created from a dataframe in R contains 60 email addresses, is written to disk, then uploaded to Slack. The csv that gets pushed to Slack then only has 48 email addresses. 

I tried using the httr::verbose function around the SlackUpload function and indeed it looks like the upload is parsing the csv first and excluding lines. I am confused why this is the case and why the logic to do so versus just uploading the entire file as is. 

I would include the files, but they have PII not appropriate for Github.

**Comment by ghost** [comment]
I'll review the Slack API docs to see what may be causing this. #ty
