### ISSUE TITLE
error in ggslackr

### ISSUE THREAD

**Issue by hrbrmstr** [mrkaye97/slackr#39]
http://stackoverflow.com/questions/38211733/error-when-trying-ggslackr-in-r

**Comment by joliverson** [comment]
[data.csv.zip](https://github.com/hrbrmstr/slackr/files/349018/data.csv.zip)

`h <- ggplot(j, aes(x=ctr_diff, y=company)) 
  h <- h + geom_point(size=.75, col="grey35") + theme_minimal()
  h <- h + theme(axis.text.y=element_blank(), axis.ticks=element_blank())
  h <- h + scale_x_continuous(label=percent) 
  h <- h + geom_vline(xintercept=0, size=.3) 
  h <- h + geom_segment(aes(x=lower, y=company, xend=upper, yend=company), size=.15, col="grey60")
  h <- h + labs(list(title=title1, x=sprintf("Difference from %s to %s", Sys.Date()-2, Sys.Date()-1)))
print(h)
ggslackr(h)`

**Comment by joliverson** [comment]
[data.csv.zip](https://github.com/hrbrmstr/slackr/files/349021/data.csv.zip)
h <- ggplot(data, aes(x=ctr_diff, y=company)) 
h <- h + geom_point(size=.75, col="grey35") + theme_minimal()
h <- h + theme(axis.text.y=element_blank(), axis.ticks=element_blank())
h <- h + scale_x_continuous(label=percent) 
h <- h + geom_vline(xintercept=0, size=.3) 
h <- h + geom_segment(aes(x=lower, y=company, xend=upper, yend=company), size=.15, col="grey60")
h <- h + labs(list(title="title1", x=sprintf("Difference from %s to %s", Sys.Date()-2, Sys.Date()-1)))
ggslackr(h)

My .slackr file matches the one referenced in the description.
**sorry for the terrible inline code. Didn't want to take the time to learn how to do it properly. I'm fairly new at asking for help on these types of forums.

**Comment by dyerlab** [comment]
Same here:

```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)
> packageVersion("slackr")
[1] ‘1.4.1’
```

Even basic data causes the problem

```
> ggslackr( qplot( rnorm(100), geom="density" ) )
Error: Each variable must have a unique name.
Problem variables: 'real_name'
```

**Comment by Breza** [comment]
I'm getting the same error. Also, I occasionally get the following error message:
`Error in fetch(key) :
  lazy-load database 'C:/Users/abreza/Documents/R/win-library/3.3/slackr/help/slackr.rdb' is corrupt`

**Comment by dyerlab** [comment]
This is a known problem, it was pointed out [here](https://github.com/hrbrmstr/slackr/issues/25)  and marked resolved but actually never fixed.  [Here](http://dyerlab.bio.vcu.edu/2016/07/08/collab-slack-r/) is my work around.  Until hrbrmstr pushes the fix up to github, I will maintain my own version.

**Comment by joliverson** [comment]
@dyerlab - I tried your workaround. I don't get the error message anymore but it isn't communicating with my slack account. I'm assuming it has something to do with my api-key, maybe?

It's still working on my other server with an older version of slackr.

**Comment by Breza** [comment]
@joliverson - Have you tried using the `slackr_bot`command? That's the only one that works for me now.

See issue https://github.com/hrbrmstr/slackr/issues/40

**Comment by gjmulder** [comment]
I think I have a fix here: https://github.com/hrbrmstr/slackr/pull/41
