### ISSUE TITLE
bug in ggslackr/dev.slackr ?

### ISSUE THREAD

**Issue by ghost** [mrkaye97/slackr#4]
I get the following errors when running the ggslackr / dev.slackr examples from the manual:

`ggslackr(qplot(mpg, wt, data=mtcars)) Error in rbindlist(l, use.names, fill) : Item 2 has 2 columns, inconsistent with item 1 which has 3 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.`

I get the same error message with any other ggplot code I run. i.e.

`ggslackr(ggplot(iris, aes(x = Species, y = Sepal.Width, fill = Species)) + geom_bar(stat="identity"))`

and yes, I created a private group in Slack. The plots in R are created as expected without errors. 
I can send messages using slackr just fine. A full api-token is in the config-file.
I am using R 3.1.1 and installed the latest slackr-package from github.

Did I miss something?

**Comment by hrbrmstr** [comment]
Should be fixed in the latest (just sync'd) update

**Comment by ghost** [comment]
Many thanks for your prompt response!
All the functions are working now with the latest version (1.22) .
