### ISSUE TITLE
Only slackr_bot is working

### ISSUE THREAD

**Issue by Breza** [mrkaye97/slackr#40]
I used the fix offered by @dyerlab and can send messages using `slackr_bot()`. However when I try `slackr()` and every other command it appears to work in RStudio but then never shows up in Slack.

**Comment by ghost** [comment]
will give this a go on Friday. completely out of pocket until then.

**Comment by gjmulder** [comment]
I think I have a fix here: https://github.com/hrbrmstr/slackr/pull/41

**Comment by Breza** [comment]
I installed your version and it fixes the most serious problems (i.e. I can actually send messages using it). However, I'm still only able to use `slackr_bot`. None of the other send functions work.

**Comment by hrbrmstr** [comment]
I just tried a bare `httr::POST` directly to the Slack API (`slackr` is not loaded at all). Y'all can try this yourselves:

```r
with_verbose(POST(url="https://slack.com/api/chat.postMessage",
                  body=list(token=Sys.getenv("SLACK_API_TOKEN"),
                            channel=slackr_chtrans(Sys.getenv("SLACK_CHANNEL")),
                            text="hello")))
```

The error is coming back from `httr::POST`, not `slackr`

**Comment by gjmulder** [comment]
That's a bit strange. I tested `slackr()` and `ggslackr()`and both work for me. I don't use `slackr_bot()`. What is the error you are getting?

**Comment by gjmulder** [comment]
I suspect there are multiple problems here:

I tested `slackr_upload()` and it works when I explicitly specify the `channels =` argument. However, when I first use `slackr_setup()` to specify channel, username, api_token, and then pass just the file name to `slackr_upload()` it silently fails to upload. The channels argument is documented as optional for `slackr_upload()`, so it should (like it does for `ggslackr()` and `slackr()`) use the channel argument from `slackr_setup()`

**Comment by voxnonecho** [comment]
Using the latest dev version, I'm still experiencing the same issue. Only `slackr_bot()` works. Everything else silently fails.

**Comment by Breza** [comment]
Same here, I'm only getting the bot function to work even when I explicitly specify the channel and other arguments.
