### ISSUE TITLE
asynchronous slackr requests

### ISSUE THREAD

**Issue by Popsch** [mrkaye97/slackr#44]
A very nice feature would be to enable asynchronous slackr() calls. At the moment, using slackr for messaging purposes to for instance keep a log of a remotely running service simply slows down the application too much.

**Comment by ghost** [comment]
May be able to take care of this with the new `future` package.

**Comment by Popsch** [comment]
I tried the future package for it with:

```
library(slackr)
library(future)

slackrSetup()
plan(lazy)
future({slackr_bot("hello")})
future({slackr_bot("world!")})
```

While this works in the console, it doesn't work when running R in a headless session, because the lazy policy never evaluates the future() statements.

It works with `plan(multicore)`, however, that significantly slows down R, because R spawns a new process to just execute that one statement. At the moment it seems that `future` has no capability to flush all pending future calls, which would be required to use `plan(lazy)`.

**Comment by JackStat** [comment]
The curl package can now submit multiple API requests at once.  Would that be an efficient method? https://github.com/jeroenooms/curl/blob/master/R/multi.R
