### ISSUE TITLE
Error using slack or slack_msg

### ISSUE THREAD

**Issue by ghost** [mrkaye97/slackr#47]
Hi guys, 

i have encountered an issue:

script:

```
library("slackr", lib.loc="~/R/win-library/3.3")
config= "~/R/config_file.dcf"
slackr_setup(config_file = config, echo = T)
slackr_msg(txt ="hello")
```

output of slackr_setup:

```
{
 "SLACK_CHANNEL": ["#general"],
  "SLACK_USERNAME": ["incoming-webhook"],
  "SLACK_ICON_EMOJI": [":ghost:"],
  "SLACK_INCOMING_URL_PREFIX": ["https://hooks.slack.com/services/XXXX/XXXX/XXXX"],
  "SLACK_API_TOKEN": ["XXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXXXXXXXX"]
} 
```

Error Message:

Error in eval(substitute(expr), envir, enclos) : 
  'id' column not found in lhs, cannot join

Thanks!

**Comment by hrbrmstr** [comment]
argh. they prbly tweaked the API again (i rarely use Slack since my org
uses FlowDock). Thx for flagging the issue.

**Comment by caseywdunn** [comment]
Just wanted to confirm that I get the same error.

**Comment by jackolney** [comment]
same error here.. 😞

**Comment by MeganBeckett** [comment]
Hi there, I'm also getting this error. Is this package still maintained, or anyone else have an alternative they would suggest?

Thanks!

**Comment by yonicd** [comment]
There is a suite of packages that together are an alternative to {slackr}. 

  - [slackteams](https://github.com/yonicd/slackteams) helps you create and manage incoming webhooks to interact with multiple teams persistently across R sessions
  - [slackblocks](https://github.com/yonicd/slackblocks) helps you post to slack from a simple message all the way to elaborate blocks
  - [slackthreads](https://github.com/yonicd/slackthreads) helps you interrogate slack messages, threads and objects
  - [slackreprex](https://github.com/yonicd/slackreprex) makes it easy to create reprex for slack
  - [slackcalls](https://github.com/yonicd/slackcalls) controls the API calls for the other packages and can be extended to all the scopes an incoming webhook can be set up for.

This how all the packages connect to each other and each badge is an active link.

|                                                                                                                                 |                                                                                                                                     |                                                                                                                                    |
| :-----------------------------------------------------------------------------------------------------------------------------: | :---------------------------------------------------------------------------------------------------------------------------------: | :--------------------------------------------------------------------------------------------------------------------------------: |
|                                                                                                                                 | slackcalls<br>[![](https://github.com/yonicd/slackcalls/workflows/R-mac/badge.svg)](https://github.com/yonicd/slackcalls)<br>↙️⬇️↘️ |                                                                                                                                    |
| slackthreads<br>[![](https://github.com/yonicd/slackthreads/workflows/R-mac/badge.svg)](https://github.com/yonicd/slackthreads) |  slackteams<br>[![](https://github.com/yonicd/slackteams/workflows/R-mac/badge.svg)](https://github.com/yonicd/slackteams)<br>⬅️➡️  | slackblocks<br>[![](https://github.com/yonicd/slackblocks/workflows/R-mac/badge.svg)](https://github.com/yonicd/slackblocks)<br>⬇️ |
|                                                                                                                                 |                                                                                                                                     |    slackreprex<br>[![](https://github.com/yonicd/slackreprex/workflows/R-mac/badge.svg)](https://github.com/yonicd/slackreprex)    |
