### ISSUE TITLE
slackr() not sending messages to groups

### ISSUE THREAD

**Issue by rontomer** [mrkaye97/slackr#50]
Hello

Since this week, I can't send messages to slack group, only to private users.
Any one else encounter this problem?
I am using the lated slackr version (1.4.2)

Thanks
Tomer

**Comment by jackolney** [comment]
are you getting `Error: 'id' column not found in lhs, cannot join`

sounds like slack might have changed their API again...

**Comment by rontomer** [comment]
No error. It just doesn't send it.
After further digging, I found the problem.
It seems that in the last call of the the slackr function, there is variable called **as_user** which is set to TRUE.
I changed it to FALSE and it works

`httr::POST(url = "https://slack.com/api/chat.postMessage", 
                     body = list(token = api_token, channel = slackr_chtrans(channel), 
                                 username = username, icon_emoji = icon_emoji, 
                                 as_user = F, text = sprintf("```%s```", output), 
                                 link_names = 1))
`

**Comment by jackolney** [comment]
Thanks for the update, I'll give it a go to see if it works for me too.

**Comment by kohleth** [comment]
I still have the same issue as of now. Need to manually turn `as_user=F`. Is this supposed to be the case?

**Comment by yonicd** [comment]
same issue as this https://github.com/hrbrmstr/slackr/issues/89#issuecomment-497796023

**Comment by ruseel** [comment]
`as_user = F` works. 

But even if `as_user = T` as slackr coded now., slackr is sending message sucessfully If `only If` `app` should be added to channel. 

Or `slackr()` called without any error or warning. But If you look at response from API(slack.com), it's body saids`not in channel`. 

----
While I am debugging and searching, I came upon docs (on internet) that saids 'chat:write:user' scope is needed. But I could successfully send message without that.

**Comment by briholt100** [comment]
> I still have the same issue as of now. Need to manually turn `as_user=F`. Is this supposed to be the case?

How does one manually adjust this?  Must one use the httr::POST function above, or is there a way to slip this in to the higher level functions (e.g., ggslackr, slackr)?
