### ISSUE TITLE
slackr_bot can not handle " " inside expressions

### ISSUE THREAD

**Issue by Javdat** [mrkaye97/slackr#54]
Demonstration:

```
a <- function(x) x
slackr_bot(a(3)) # Works
slackr_bot(a("test")) # Fails

slackr_bot("test") # Works (fixed by https://github.com/hrbrmstr/slackr/pull/37)
slackr_bot(paste("test")) # Fails
```

Fail generated is ` Bad Request (HTTP 400).`

This is related to 'side fix' of https://github.com/hrbrmstr/slackr/pull/37. There, I have fixed error when `eval(expr)` returns with `" "`. But here the `expr` itself contains `" "`

**Comment by Breza** [comment]
I'm also having this problem in a scheduled task I use to notify me of problems

**Comment by Breza** [comment]
Here's a reproducible example of the kind of script that I really wish I could write. Being able to send customized messages through Slack would be a huge improvement.

```
weekday <- lubridate::wday(Sys.Date(), label = TRUE, abbr = FALSE)
slackr_bot(paste("Today is", weekday))
```

**Comment by yonicd** [comment]
you can use the following to pass to slack the examples both of you ran

```r
slackr::slackr({paste("Today is", weekday)})
```

as for the scheduled tasks, i would register the function with `slackr::register_onexit()` and then run the script as is.

small example

```r
library(slackr)

slackr_setup()

myfun <- function(x){x+5}

#creates slack_myfun in global envir that has an on.exit attached to it
slackr::register_onexit(myfun,{
  weekday <- lubridate::wday(Sys.Date(), label = TRUE, abbr = FALSE)
  paste("Today is", weekday)
})

slack_myfun(3)
```

**Comment by Javdat** [comment]
I haven't looked at this issue in a long time as I have implemented a workaround of writing a message to variable and passing a variable to `slackr_bot` and moved on.

But the solution offered by @yonicd does not actually solve this issue. The issue specifically relates to `slackr_bot` which is slack connection with incoming web-hook and without API token (unlike `slackr`).

And as far as I can see the issue is not solved for `slackr_bot`.
