### ISSUE TITLE
 slackr(str(iris)) Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column

### ISSUE THREAD

**Issue by vipula86** [mrkaye97/slackr#58]
On command: slackr(str(iris))
this Error is coming out: Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column

How to fix it?

**Comment by ronnyli** [comment]
I would recommend running
```
debugonce(slackr)  # could use debug(slackr) but then you'd have to remember to undebug(slackr) later
slackr(str(iris))
```
Then step through the function one line at a time (click the Next button) until you find the exact point where it's breaking.

If your problem is at this line: 
```
resp <- POST(url = "https://slack.com/api/chat.postMessage", 
    body = list(token = api_token, channel = slackr_chtrans(channel), 
        username = username, icon_emoji = icon_emoji, as_user = TRUE, 
        text = sprintf("```%s```", output), link_names = 1))
```
then run `jsonlite::fromJSON(httr::content(resp, as="text"))` while still in debug mode. You'll get a _much_ more helpful error such as:
```
Browse[2]> jsonlite::fromJSON(httr::content(resp, as="text"))
$ok
[1] FALSE

$error
[1] "missing_scope"

$needed
[1] "chat:write:user"

$provided
[1] "identify,incoming-webhook,channels:read,groups:read,im:read,users:read,chat:write:bot,files:write:user"
```

**Comment by simeneide** [comment]
How can you get anything out of the resp object if it fails before that? I have the same issue...

**Comment by ronnyli** [comment]
Hi Simen, can you share the line the function breaks at?

**Comment by simeneide** [comment]
It breaks when writing the resp object (ie the line you quoted above). However, when I look at the output object I do not see my message but this:

`"debug: on.exit({\n    sink()\n    close(fil)\n})\ndebug: pf <- parent.frame()\ndebug: evalVis <- function(expr) withVisible(eval(expr, pf))\ndebug: for (i in seq_along(args)) {\n    expr <- args[[i]]\n    tmp <- switch(mode(expr), expression = {\n        cat(sprintf(\"> %s\\n\", deparse(expr)))\n        lapply(expr, evalVis)\n    }, call = , name = {\n        cat(sprintf(\"> %s\\n\", deparse(expr)))\n        list(evalVis(expr))\n    }, integer = , double = , complex = , raw = , logical = , \n        numeric = cat(sprintf(\"%s\\n\\n\", as.character(expr))), \n        character = cat(sprintf(\"%s\\n\\n\", expr)), stop(\"mode of argument not handled at present by slackr\"))\n    for (item in tmp) if (item$visible) {\n        print(item$value)\n        cat(\"\\n\")\n    }\n}\ndebug: expr <- args[[i]]\ndebug: tmp <- switch(mode(expr), expression = {\n    cat(sprintf(\"> %s\\n\", deparse(expr)))\n    lapply(expr, evalVis)\n}, call = , name = {\n    cat(sprintf(\"> %s\\n\", deparse(expr)... <truncated>`

Doesnt look like the text string "Hello" that I am trying to send...

**Comment by ronnyli** [comment]
Are you seeing that weird string in Slack? That looks like a side effect of being in debug mode when running `slackr`.  Can you try running `undebug(slackr)` then `slackr('Hello')` again?

**Comment by MST2803** [comment]
I have the same issue.

But I can not execute

jsonlite::fromJSON(httr::content(resp, as="text"))

**Comment by ronnyli** [comment]
Hi @MST2803, are you in debug mode when you try to run that line and does `resp` exist at the time? And just to be safe, do you have `jsonlite` and `httr` installed?

**Comment by MST2803** [comment]
Hi Ronny, 

jsonlite and httr is installed.

i am in debug mode with:

debugonce(slackr_msg)
slackr_msg( txt ="hello")

I run each line of code until:

 resp <- POST(url = "https://slack.com/api/chat.postMessage", 
    body = list(token = api_token, channel = slackr_chtrans(channel), 
      username = username, icon_emoji = icon_emoji, text = output, 
      as_user = TRUE, link_names = 1, ...))

I tried to run jsonlite::fromJSON(httr::content(resp, as="text")) before and after resp

when I go one function below i guess it breaks at req

function (url = NULL, config = list(), ..., body = NULL, encode = c("multipart", 
  "form", "json", "raw"), handle = NULL) 
{
  encode <- match.arg(encode)
  hu <- handle_url(handle, url, ...)
  req <- request_build("POST", hu$url, body_config(body, match.arg(encode)), 
    as.request(config), ...)
  request_perform(req, hu$handle$handle)
}

**Comment by ronnyli** [comment]
Here's what it looks like when I run `debugonce` (note that I wait for `resp` to exist before running `jsonlite`). You can compare with your own experience to see if there was a mistake made at some point.
```
> debugonce(slackr_msg)
> slackr_msg(txt = "hello", channel = "#totallyfakechannellzzz", api_token = "alsofake")
debugging in: slackr_msg(txt = "hello", channel = "#totallyfakechannellzzz", 
    api_token = "alsofake")
debug: {
    if (api_token == "") {
        stop("No token specified. Did you forget to call slackr_setup()?", 
            call. = FALSE)
    }
    if (icon_emoji != "") {
        icon_emoji <- sprintf(", \"icon_emoji\": \"%s\"", icon_emoji)
    }
    output <- paste0(txt, collapse = "\n\n")
    loc <- Sys.getlocale("LC_CTYPE")
    Sys.setlocale("LC_CTYPE", "C")
    on.exit(Sys.setlocale("LC_CTYPE", loc))
    resp <- POST(url = "https://slack.com/api/chat.postMessage", 
        body = list(token = api_token, channel = slackr_chtrans(channel), 
            username = username, icon_emoji = icon_emoji, text = output, 
            as_user = TRUE, link_names = 1, ...))
    warn_for_status(resp)
    return(invisible())
}
Browse[2]> n
debug: if (api_token == "") {
    stop("No token specified. Did you forget to call slackr_setup()?", 
        call. = FALSE)
}
Browse[2]> n
debug: if (icon_emoji != "") {
    icon_emoji <- sprintf(", \"icon_emoji\": \"%s\"", icon_emoji)
}
Browse[2]> n
debug: icon_emoji <- sprintf(", \"icon_emoji\": \"%s\"", icon_emoji)
Browse[2]> n
debug: output <- paste0(txt, collapse = "\n\n")
Browse[2]> n
debug: loc <- Sys.getlocale("LC_CTYPE")
Browse[2]> n
debug: Sys.setlocale("LC_CTYPE", "C")
Browse[2]> n
debug: on.exit(Sys.setlocale("LC_CTYPE", loc))
Browse[2]> n
debug: resp <- POST(url = "https://slack.com/api/chat.postMessage", 
    body = list(token = api_token, channel = slackr_chtrans(channel), 
        username = username, icon_emoji = icon_emoji, text = output, 
        as_user = TRUE, link_names = 1, ...))
Browse[2]> n
debug: warn_for_status(resp)
Browse[2]> jsonlite::fromJSON(httr::content(resp, as="text"))
$ok
[1] FALSE

$error
[1] "invalid_auth"
```

**Comment by ronnyli** [comment]
If you aren't able to copy what I did due to the code breaking at `resp` then you might want to check that the inputs being passed to `POST` are good. For example, what is your value for `channel` and what happens when you run `slackr_chtrans(channel)`, etc. (Hint: it shouldn't result in `logical(0)`)

**Comment by MST2803** [comment]
Okay, my code breaks at resp. So I have no chance to use Json.

`> debugonce(slackr_msg)
> slackr_msg( txt ="hello")
debugging in: slackr_msg(txt = "hello")
debug: {
    if (api_token == "") {
        stop("No token specified. Did you forget to call slackr_setup()?", 
            call. = FALSE)
    }
    if (icon_emoji != "") {
        icon_emoji <- sprintf(", \"icon_emoji\": \"%s\"", icon_emoji)
    }
    output <- paste0(txt, collapse = "\n\n")
    loc <- Sys.getlocale("LC_CTYPE")
    Sys.setlocale("LC_CTYPE", "C")
    on.exit(Sys.setlocale("LC_CTYPE", loc))
    resp <- POST(url = "https://slack.com/api/chat.postMessage", 
        body = list(token = api_token, channel = slackr_chtrans(channel), 
            username = username, icon_emoji = icon_emoji, text = output, 
            as_user = TRUE, link_names = 1, ...))
    warn_for_status(resp)
    return(invisible())
}
Browse[2]> n
debug: if (api_token == "") {
    stop("No token specified. Did you forget to call slackr_setup()?", 
        call. = FALSE)
}
Browse[2]> n
debug: if (icon_emoji != "") {
    icon_emoji <- sprintf(", \"icon_emoji\": \"%s\"", icon_emoji)
}
Browse[2]> n
debug: icon_emoji <- sprintf(", \"icon_emoji\": \"%s\"", icon_emoji)
Browse[2]> n
debug: output <- paste0(txt, collapse = "\n\n")
Browse[2]> n
debug: loc <- Sys.getlocale("LC_CTYPE")
Browse[2]> n
debug: Sys.setlocale("LC_CTYPE", "C")
Browse[2]> n
debug: on.exit(Sys.setlocale("LC_CTYPE", loc))
Browse[2]> n
debug: resp <- POST(url = "https://slack.com/api/chat.postMessage", 
    body = list(token = api_token, channel = slackr_chtrans(channel), 
        username = username, icon_emoji = icon_emoji, text = output, 
        as_user = TRUE, link_names = 1, ...))
Browse[2]> s
debugging in: POST(url = "https://slack.com/api/chat.postMessage", body = list(token = api_token, 
    channel = slackr_chtrans(channel), username = username, icon_emoji = icon_emoji, 
    text = output, as_user = TRUE, link_names = 1, ...))
debug: {
    encode <- match.arg(encode)
    hu <- handle_url(handle, url, ...)
    req <- request_build("POST", hu$url, body_config(body, match.arg(encode)), 
        as.request(config), ...)
    request_perform(req, hu$handle$handle)
}
Browse[3]> n
debug: encode <- match.arg(encode)
Browse[3]> n
debug: hu <- handle_url(handle, url, ...)
Browse[3]> n
debug: req <- request_build("POST", hu$url, body_config(body, match.arg(encode)), 
    as.request(config), ...)
Browse[3]> s
debugging in: request_build("POST", hu$url, body_config(body, match.arg(encode)), 
    as.request(config), ...)
debug: {
    extra <- list(...)
    extra[has_name(extra)] <- NULL
    req <- Reduce(request_combine, extra, init = request())
    req$method <- method
    req$url <- url
    req
}
Browse[4]> n
debug: extra <- list(...)
Browse[4]> s
debugging in: body_config(body, match.arg(encode))
debug: {
    if (identical(body, FALSE)) 
        return(config(post = TRUE, nobody = TRUE))
    if (inherits(body, "form_file")) {
        con <- file(body$path, "rb")
        size <- file.info(body$path)$size
        return(c(config(post = TRUE, readfunction = function(nbytes, 
            ...) {
            if (is.null(con)) return(raw())
            bin <- readBin(con, "raw", nbytes)
            if (length(bin) < nbytes) {
                close(con)
                con <<- NULL
            }
            bin
        }, postfieldsize_large = size), content_type(body$type)))
    }
    if (is.character(body) || is.raw(body)) 
        return(body_raw(body, type = type))
    if (is.null(body)) 
        return(body_raw(raw()))
    if (!is.list(body)) {
        stop("Unknown type of `body`: must be NULL, FALSE, character, raw or list", 
            call. = FALSE)
    }
    body <- compact(body)
    encode <- match.arg(encode)
    if (encode == "raw") {
        body_raw(body)
    }
    else if (encode == "form") {
        body_raw(compose_query(body), "application/x-www-form-urlencoded")
    }
    else if (encode == "json") {
        body_raw(jsonlite::toJSON(body, auto_unbox = TRUE), "application/json")
    }
    else if (encode == "multipart") {
        if (!all(has_name(body))) 
            stop("All components of body must be named", call. = FALSE)
        request(fields = lapply(body, as_field))
    }
}
Browse[5]> n
debug: if (identical(body, FALSE)) return(config(post = TRUE, nobody = TRUE))
Browse[5]> s
debugging in: identical(body, FALSE)
debug: .Internal(identical(x, y, num.eq, single.NA, attrib.as.set, ignore.bytecode, 
    ignore.environment, ignore.srcref))`

**Comment by MST2803** [comment]
Hi ronnyli,

i just looked deeper in it, but i can not figure out how to debug it.

The problem is related to slack_ims:

`debug: {
    chan <- slackr::slackr_channels(api_token)
    **users <- slackr::slackr_ims(api_token)**
    groups <- slackr_groups(api_token)
    chan$name <- sprintf("#%s", chan$name)
    users$name <- sprintf("@%s", users$name)
    chan_list <- data_frame(id = character(0), name = character(0))
    if (length(chan) > 0) {
        chan_list <- bind_rows(chan_list, chan[, c("id", "name")])
    }
    if (length(users) > 0) {
        chan_list <- bind_rows(chan_list, users[, c("id", "name")])
    }
    if (length(groups) > 0) {
        chan_list <- bind_rows(chan_list, groups[, c("id", "name")])
    }
    chan_list <- dplyr::distinct(chan_list)
    chan_list <- data.frame(chan_list, stringsAsFactors = FALSE)
    chan_xref <- chan_list[chan_list$name %in% channels, ]
    ifelse(is.na(chan_xref$id), as.character(chan_xref$name), 
        as.character(chan_xref$id))
}
Browse[7]> n`

**Comment by ronnyli** [comment]
Looks like you're very close to the problem! Something is probably wrong with your API token. If you haven't made any of the obvious sources of error (i.e., messed up when copy-pasting it, didn't save it in the proper format in `~/.slackr`, etc.) then you should check if your token has the necessary permissions that SlackR requires.

I think these are all the permissions but I might be wrong:

- identify
- channels:read
- groups:read
- im:read
- mpim:read
- users:read
- usergroups:read
- chat:write:user
- chat:write:bot
- files:write:user 

I found them by searching `"slack.com/api/"` on the slackr repo.

**Comment by deann88** [comment]
Had similar issues. The permissions I had to add in addition to the ones above from @ronnyli were:
    1. channels:write  - to be able to write to public channels
    2. groups:write  - to be able to write to private channels 

Had to use `text_slackr` instead of just slackr as the latter is not able to write to get private channels due to the use of `channels.list` method instead of `groups.list` method.
