### ISSUE TITLE
can slackr fail noisily if Slack responds with FALSE ok status?

### ISSUE THREAD

**Issue by ronnyli** [mrkaye97/slackr#59]
I was getting errors like `'id' column not found in lhs`and also cases where slackr would succeed but no messages would appear on Slack. To find the issue I ended up having to run `debug(slackr)` and stepping through the function until
```
resp <- POST(url = "https://slack.com/api/chat.postMessage", 
    body = list(token = api_token, channel = slackr_chtrans(channel), 
        username = username, icon_emoji = icon_emoji, as_user = TRUE, 
        text = sprintf("```%s```", output), link_names = 1))
```
and executing `jsonlite::fromJSON(httr::content(resp, as="text"))` while in debug mode. This would reveal the actual error such as:
```
$ok
[1] FALSE

$error
[1] "missing_scope"

$needed
[1] "chat:write:user"

$provided
[1] "identify,incoming-webhook,channels:read,groups:read,im:read,users:read,chat:write:bot,files:write:user"
```
It'd be great if slackr could fail loudly when `jsonlite::fromJSON(...)$ok==FALSE` and return Slack's error message.

Thanks!

**Comment by colearendt** [comment]
A related case:

Got this from the API when trying to post a direct message:
```
"{\"ok\":false,\"error\":\"missing_scope\",\"needed\":\"im:read\",\"provided\":\"identify,incoming-webhook,users.profile:read,chat:write:bot\"}"
```

The output / error message I received in R:
```
Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column
```

**Comment by yonicd** [comment]
Those messages from the API a somewhat new relative to when slackr was written. There wasnt a reason to return the error message from the API originally. 

If I get to it I can add in error handlers into the package, you are welcome to add a PR if you want.

**Comment by econosopher** [comment]
@yonicd Can you merge the pull request? This is ready to go, and a big win for the app.
