### ISSUE TITLE
slackr_channel_history problem

### ISSUE THREAD

**Issue by tansaku** [mrkaye97/slackr#63]
we can't get slackr_channel_history to work
```
> history <- slackr_channel_history(test_token,"C0285CSUF",earliest_date, latest_date, 99L)
Channel C0285CSUF does not exist.
Channel C0285CSUF has no new messages.
```
seems like the code is not exposing the actual error message:

```
error = function(e) {
    message(paste("Channel", channel, "does not exist."))
  })
```
might be good to display the e.message - we know our channel exists and the token is correct - other functions like slackr channels are working ...

**Comment by raybuhr** [comment]
It's expecting the channel name and automatically looks up the id for you.

**Comment by raybuhr** [comment]
I'm wondering whether it's more common to pass the channel name or Id... The rest of this package seems to accept the channel by name, which is easier to remember, but perceptible to change.

**Comment by tansaku** [comment]
good to support both perhaps?  either way, would be great if the actual error message could be relayed rather than being thrown away ...

**Comment by raybuhr** [comment]
I submitted PR #65 to deprecate `slackr_channel_history` in favor of `history_slackr`, as well as modified the error message returned to also relay the exact message from Slack in case you still want to use it.

**Comment by yonicd** [comment]
merged https://github.com/hrbrmstr/slackr/pull/65
