### ISSUE TITLE
duplicated functionality for slack_history

### ISSUE THREAD

**Issue by yonicd** [mrkaye97/slackr#64]
there was already a function for this in the package.

https://github.com/hrbrmstr/slackr/blob/master/R/history_slackr.R

most of the piping for other functions is already builtin for the one i added

**Comment by raybuhr** [comment]
I'm willing to retract/deprecate the history function I submitted and forward any calls to it to your new version. I would like to add the search by date range feature my history function adds, if that's cool with you, though.

**Comment by yonicd** [comment]
that's fine. thanks

**Comment by yonicd** [comment]
btw that [option](https://github.com/hrbrmstr/slackr/blob/master/R/history_slackr.R#L5) is there already

**Comment by raybuhr** [comment]
PR #65 deprecates the `slackr_channel_history` function in favor of `history_slackr`

**Comment by yonicd** [comment]
merged https://github.com/hrbrmstr/slackr/pull/65
