### ISSUE TITLE
latex equation

### ISSUE THREAD

**Issue by zippeurfou** [mrkaye97/slackr#66]
This is more a feature request but it would be nice to be able to parse some latex equation.
Slack does not have an easy way to read latex and I feel like this would be a perfect match.

**Comment by yonicd** [comment]
`tex_slacker` uses [texPreview](https://github.com/metrumresearchgroup/texPreview), so you should be able to parse any tex and send it to slack

example:

```r
tex_slackr(obj = '\\begin{equation}\\alpha+\\beta\\end{equation}')
```
<img width="570" alt="screen shot 2017-10-30 at 15 49 44" src="https://user-images.githubusercontent.com/1755487/32192320-375f6b0e-bd8a-11e7-9d45-b081741e359e.png">

**Comment by zippeurfou** [comment]
Aw awesome! closing it since it does the job perfectly 👍

**Comment by zippeurfou** [comment]
@yonicd 
would you know why it does not works well with latex inside xtable?
i.e.
```
x <- as.vector(rbind(1, paste("\\frac{",1, "}{", 2, "}", sep ="" ))) 
y <- as.vector(rbind(2, paste("\\frac{",2, "}{", 3, "}", sep ="" )))    
print(xtable(cbind(x,y)), sanitize.text.function=identity)
```
produce:
```
% latex table generated in R 3.4.1 by xtable 1.8-2 package
% Thu Nov  2 10:56:35 2017
\begin{table}[ht]
\centering
\begin{tabular}{rll}
  \hline
 & x & y \\
  \hline
1 & 1 & 2 \\
  2 & \frac{1}{2} & \frac{2}{3} \\
   \hline
\end{tabular}
\end{table}
```
but if I do:
```
 tex_slackr(print(xtable(cbind(x,y)), sanitize.text.function=identity))
```
I get this:
```
% latex table generated in R 3.4.1 by xtable 1.8-2 package
% Thu Nov  2 10:57:25 2017
\begin{table}[ht]
\centering
\begin{tabular}{rll}
  \hline
 & x & y \\
  \hline
1 & 1 & 2 \\
  2 & \frac{1}{2} & \frac{2}{3} \\
   \hline
\end{tabular}
\end{table}
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Error in magick_image_readpath(path, density, depth) :
  Magick: unable to open image '/var/folders/qw/q35rllhn5cgfsplb039w46380000gn/T//Rtmp1CrVjD/slack/slackDoc.pdf': No such file or directory @ error/blob.c/OpenBlob/3109
```
Note that without the sanitize it does works but do not output convert the latex equation (which is expected):
```
tex_slackr(print(xtable(cbind(x,y))))
```
![image](https://user-images.githubusercontent.com/4520383/32332875-e54ad40e-bfbc-11e7-8f44-0d9444487e4c.png)

**Comment by yonicd** [comment]
add `$*$` in your equations

**Comment by zippeurfou** [comment]
wohoo it works. that's my bad. thank you!
