### ISSUE TITLE
Add a note to documentation explaining where you get an API token

### ISSUE THREAD

**Issue by smithjd** [mrkaye97/slackr#67]
This page provides a critical piece of information: https://api.slack.com/custom-integrations/legacy-tokens

**Comment by cderv** [comment]
Does this mean {slackr} works with legacy-tokens ?

**Comment by cderv** [comment]
I manage to make it work by creating an app but it was not easy to know which scope is required so that every functions in this 📦 .

I understand from your issue that it may be possible that this packages is intended to work instead with legacy token (or test token for slack). Am I right ?

**Comment by rosseji** [comment]
Can concur that it was a legacy token that worked for me

**Comment by joelgombin** [comment]
Legacy tokens are not supported anymore, is there a way to work with apps credentials when an API token is required in the package? (e.g. slackr_upload)

**Comment by obarisk** [comment]
create an app [slack app](https://api.slack.com/apps)

**Comment by yonicd** [comment]
there is no need to create an app you can use the R package [slackteams](https://github.com/yonicd/slackteams) instead.
