### ISSUE TITLE
slackr_upload fails with .gif

### ISSUE THREAD

**Issue by tomauer** [mrkaye97/slackr#68]
I'm on slackr 1.4.2 and am attempting to upload a .gif file to a channel, but it's not working. I used:

`httr::with_verbose(slackr_upload(gif_path))`

And got:

<- HTTP/1.1 504 Gateway Time-out
<- Content-Type: text/html
<- Transfer-Encoding: chunked
<- Connection: close
<- Date: Mon, 06 Nov 2017 10:49:10 GMT
<- Last-Modified: Fri, 05 Feb 2016 23:46:05 GMT
<- Server: AmazonS3
<- Content-Encoding: gzip
<- Vary: Accept-Encoding
<- Age: 12974
<- X-Cache: Error from cloudfront
<- Via: 1.1 ac094a1c1bf8cbfbb98e93fa2b2431c0.cloudfront.net (CloudFront)
<- X-Amz-Cf-Id: lscQ-wJV7XPrivGJzsUsxX9LhoVEG-_zCjt127SB5ko--INRxNBXQA==

I have successfully used slackr() to post to the channel and am able to successfully post a .png file to the channel. I have also tried adding channel explicitly and it doesn't work. Finally, I have also confirmed that the gif exists at the path supplied.

**Comment by yonicd** [comment]
it looks like slack is returning a 504 error which indicates that something on their side is going wrong.

@hrbrmstr any thoughts on something else that it could be?

this is the result from the post call

```r
$`content-type`
[1] "text/html"

$`transfer-encoding`
[1] "chunked"

$connection
[1] "close"

$date
[1] "Wed, 08 Mar 2017 05:48:31 GMT"

$`last-modified`
[1] "Fri, 05 Feb 2016 23:46:05 GMT"

$server
[1] "AmazonS3"

$`content-encoding`
[1] "gzip"

$vary
[1] "Accept-Encoding"

$age
[1] "18299"

$`x-cache`
[1] "Error from cloudfront"

$via
[1] "1.1 a497be2b49819cefc328d1fdef94a6a1.cloudfront.net (CloudFront)"

$`x-amz-cf-id`
[1] "PpF68_p7IS4dTAwnxRol2RjRTsnqm8N-G-lYiYZbmX19kMI3GVhW8A=="

```
