### ISSUE TITLE
history_slackr and private channels

### ISSUE THREAD

**Issue by hathawayj** [mrkaye97/slackr#76]
When I use `history_slackr(1, "private_channel") it returns `NULL`.  I can see the private channels through a call to `slackr_groups()`.  However, none of those private channels will return data with a call to `history_slack()`.

I used <https://api.slack.com/custom-integrations/legacy-tokens> to create my tokens.  I have tested and I can use `history_slackr()` to get data from public channels.

**Comment by sentieonycdev** [comment]
I have the same issue as above.  I can post to private channels but history_slackr returns null.

**Comment by MrAE** [comment]
It doesn't seem that user tokens allow history access to private channels.  See below 

>User tokens gain the "old world" resource-based OAuth scopes requested in the installation process (example: asking for channels:history grants access a user token access to channels.history for any public channel)

from https://api.slack.com/docs/token-types#user
