### ISSUE TITLE
Error: no token specified on Ubuntu 16.04

### ISSUE THREAD

**Issue by babycamel** [mrkaye97/slackr#78]
Doesn't appear to work on Ubuntu 16.04. I am getting the Error: No toek specified. I tried it both with the Cran version and with the latest github version.  Slack no longer requires a token, so this appears to be a bug.

Thanks would love to sue this would make things a lot easier.

**Comment by zdk123** [comment]
To add more information, I also saw this error on macOS when sending data through the `slackr` function. Setting up a [legacy token](https://api.slack.com/custom-integrations/legacy-tokens) did work, as well as `slackr_bot` with just the webhook.

I'm not sure this actually a bug.

**Comment by zdk123** [comment]
Update again. You must have, like me, used the incoming webhook app. You instead need to 'build' your own [app](https://api.slack.com/) and add a webhook integration and a bot. The bot will have you an oauth token that you can use with this package.

**Comment by ajzz** [comment]
@babycamel 
With recent changes in Slack's APIs, as you mentioned, you only need to create a new app and incoming webhook URL to use `sclacrk::slack_bot` function to write to a channel.

Note the API specs have changed and the old `slack_bot` function needs to be updated to the new API spec and JSON payload. I've got a PR and working branch here being used in production if you need it: https://github.com/ajzz/slackr
