### ISSUE TITLE
Support for new Slack webhook format

### ISSUE THREAD

**Issue by davidski** [mrkaye97/slackr#8]
Slack has changed the format of their webhook URLs and no longer provides a static base with a single token parameter. Opening a place holder issue until I get a chance to hack in support for URLs in the format of `https://hooks.slack.com/services/XXXXX/XXXXX/XXXXX`.

**Comment by hrbrmstr** [comment]
thx. DBIR season has us exchanging R code on an internal gitlab environment (due to the sensitivity of the data) so we hadn't noticed this. I'll poke at it when i get a chance, too.

**Comment by davidski** [comment]
What do you think of dropping support for the old webhook + token format in favor of the new webhook-only format? I believe even older accounts can create webhooks in the new format.

**Comment by jefferis** [comment]
Hi @davidski, Did you do any work on this?

@hrbrmstr AFAICS the new style webhooks are unusable with the current version of `slackr::slack_bot`. For example 

old style including token:

```
"http://myslack.slack.com/services/hooks/incoming-webhook?token=XXXXXXXXXXXXXX"
```

new style, no token:

```
https://hooks.slack.com/services/XXXXX/XXXXX/XXXXX
```

but inside the `slack_bot` function, it is assumed that URLs are always of the old style

```
POST(url=paste0(incoming_webhook_url, "token=", token), ...
```

and posting to a new style url after appending a token fails with a 404.
