### ISSUE TITLE
slackrUpload command does not upload png file

### ISSUE THREAD

**Issue by aumdavis** [mrkaye97/slackr#81]
I started using slackr and it works fine for sending messages.  However, when I try to upload a file such as an image, nothing happens.  The command seems to run and I don't get any error messages, but nothing happens on the slack channel.  Here is my code and I am attaching the verbose log file from the slackrUpload command:

library(slackr)
slackr_setup(channel="#alerts", username="Mark Davis", 
             incoming_webhook_url = "****", 
             api_token = "****", echo = F)
image_png <- "c:/mark/consulting/dreamcloud/alert_picture.png"
httr::with_verbose(slackrUpload(filename = image_png))

**Comment by ajzz** [comment]
@aumdavis your personal token is in clear in the slackr.log file under `form-data` section, you might want to roll your token asap. It's able to list all 300+ slack users and contacts from Nectaxxx. 

Slack's permission & scope system is in flux and this package is broken in many places as per disclaimer in Readme.

**Comment by aumdavis** [comment]
Thanks for the heads up!  I removed the file and generated a new token.
