### ISSUE TITLE
delete_slackr() function not loading from CRAN package

### ISSUE THREAD

**Issue by j-Rinehart** [mrkaye97/slackr#85]
The delete_slackr() function doesn't seem to be loading with a CRAN install of the package.  Has that been depreciated?  Is there another way to delete a message?

**Comment by yonicd** [comment]
`delete_slackr` is not in the current [CRAN release](https://github.com/cran/slackr/tree/master/R), it was added after the last CRAN release.

you can install the github version using

```r
remotes::install_github('hrbrmstr/slackr')
```

**Comment by j-Rinehart** [comment]
Got it...thanks!
