### ISSUE TITLE
Username not 'used'

### ISSUE THREAD

**Issue by mraess** [mrkaye97/slackr#87]
Hi,

I was able to set slackR up successfully and am able to post into a Slack channel. However, it always uses my actual username and not the one I set in the <slackr_setup()> function.

Is there anything I need to do besides providing the api_token and incoming_webhook_url? I set up the slackR app with my Slack account. Also, is there any way oAuth support is coming for slackR anytime soon?

**Comment by yonicd** [comment]
oAuth has been a problem point for me too for a while now. Those two things should be enough.
