### ISSUE TITLE
Difference betwen slackr() and slackrBot()

### ISSUE THREAD

**Issue by davidski** [mrkaye97/slackr#9]
Apart from using the API token vs a webhook, is there a difference between using `slackr()` and `slackrBot()`? Apart from different default emoji, they both look to appear in Slack the same way. If the only difference is the credentials required, might refactoring to have a unified post to slack interface be acceptable?

**Comment by jefferis** [comment]
I haven't studied this too carefully, but from what I can see
1. You can do anything with the generic web API (`slackr`) that you can do with the webhook API (`slackrBot`) BUT
2. the webhook API integrations will have default properties such as user/channel/emoji. I don't see how you can know what these are if you want to use the web API.

Therefore I think `slackr()` and `slackrBot()` have some unique functionality and should both be kept. On the other hand the documentation is honestly somewhat confusing – especially given the problem for new style webhooks in #8.
