### ISSUE TITLE
delete_slackr() not working

### ISSUE THREAD

**Issue by enricodata** [mrkaye97/slackr#90]
Hi,

I can correctly send messages to slack with the following:
slackr("hello", channel="mychannel")
but the delete_slackr function is not working.

I am using the slackr version 1.5 from github.

I tried with both the following and it does not work
delete_slackr(count = 1, channel = '#mychannel')
delete_slackr(count = 1, channel = 'mychannel')

Do you have any suggestions?

Also I would like to know how to delete messages that appear sent from slackr APP

**Comment by yonicd** [comment]
same issue as this https://github.com/hrbrmstr/slackr/issues/89#issuecomment-497796023
