### ISSUE TITLE
history_slackr() does not install

### ISSUE THREAD

**Issue by matthewdwood82** [mrkaye97/slackr#93]
I can see ~/R/history_slackr.R file with associated function, but it does not install when I install.packages("slackr") or devtools::install_github("hrbrmstr/slackr").

**Comment by daranzolin** [comment]
I had the same problem, but I don't think it's related to `slackr`; missing exports happened with another package I installed too. Some combination of restarting, reinstalling, and updating R eventually worked.

**Comment by matthewdwood82** [comment]
Thanks for the note, looking harder it appears that history_slackr() is only in the devtools install version. Removing and reinstalling this version of the package did the trick.
